name: Test the action

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
